import "./globals.css";
import { UserProvider } from "../context/UserContext";
import ChakraProvider from "../components/ChakraProvider";
import { SearchProvider } from "../context/SearchContext";
import theme from "./theme";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
 

  return (
    <html lang="en">
      <UserProvider>
        <body>
          <ChakraProvider theme={theme}>
            <SearchProvider>
              <main>
              {children}
              </main>
            </SearchProvider>
          </ChakraProvider>
        </body>
      </UserProvider>
    </html>
  );
}
